version: '2.4'
services:
    oauth-proxy:
        build: .
        restart: always
        ports:
            - 80:80
        environment:
            GH_CLIENT_ID: my-client-id
            GH_CLIENT_SECRET: my-client-secret
            GH_USERS: my-user-1, my-user-2, my-user-3
            BACKEND_URL: http://my-backend:80
            PUBLIC_URL: http://my-server.com
